language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
script: "python setup.py test"
before_install:
  - pip install mediagoblin lxml pillow
  # Workaround but in mediagoblin.tests.tools:fixture_media_entry
  - find . -name tools.py | grep 'mediagoblin/tests/tools.py' | xargs sed -i 's/entry.uploader = uploader/entry.actor = uploader/g'
