language: python
python:
  - "2.7"
  #- "3.4"
  - "3.5"
script: "python setup.py test"
before_install:
  - pip install mediagoblin lxml pillow
  # Prevent alembic migrations from running: it won't work due to missing alembic config and script folder for migrations.
  - find /home/travis/virtualenv/ -name tools.py | grep mediagoblin/tests/ | xargs sed -i 's/run_dbupdate(app/#run_dbupdate(app/g'
  - find /home/travis/virtualenv/ -name __init__.py | grep mediagoblin/init/ | xargs sed -i 's/run_alembic_migrations(db/#run_alembic_migrations(db/g'
